### ISSUE TITLE
Compose Sequence keybind throws exception on Linux

### ISSUE THREAD

**Issue by tangledhelix** [DistributedProofreaders/guiguts-py#301]
With the current keybind for Compose Sequence, an exception is thrown at start on Ubuntu Linux.

I've tried escaping the `;` using either `\;` or `\\;` but the exception is thrown in every case. Changing to an alphabetic character (e.g. `Cmd/Ctrl+Q`) resolves the exception.

- Ubuntu 22.04.4 LTS (Jammy Jellyfish)
- Python 3.11.0

```
$ poetry run guiguts
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/ubuntu/guiguts-py/src/guiguts/application.py", line 778, in main
    Guiguts().run()
    ^^^^^^^^^
  File "/home/ubuntu/guiguts-py/src/guiguts/application.py", line 94, in __init__
    self.init_menus()
  File "/home/ubuntu/guiguts-py/src/guiguts/application.py", line 348, in init_menus
    self.init_tools_menu()
  File "/home/ubuntu/guiguts-py/src/guiguts/application.py", line 565, in init_tools_menu
    unicode_menu.add_button(
  File "/home/ubuntu/guiguts-py/src/guiguts/mainwindow.py", line 107, in add_button
    maintext().key_bind(key_event, lambda _event: command(), bind_all=bind_all)
  File "/home/ubuntu/guiguts-py/src/guiguts/maintext.py", line 345, in key_bind
    self.bind_event(lk, handler, bind_all=bind_all)
  File "/home/ubuntu/guiguts-py/src/guiguts/maintext.py", line 269, in bind_event
    super().bind(event_string, break_func, add)
  File "/usr/lib/python3.11/tkinter/__init__.py", line 1448, in bind
    return self._bind(('bind', self._w), sequence, func, add)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/tkinter/__init__.py", line 1402, in _bind
    self.tk.call(what + (sequence, cmd))
_tkinter.TclError: bad event type or keysym ";"
```

**Comment by srjfoo** [comment]
> Changing to an alphabetic character (e.g. `Cmd/Ctrl+Q`) resolves the exception.

Please, not `Q`. I think that should be reserved for quitting the application.

**Comment by tangledhelix** [comment]
To be clear, I wasn't proposing Q. It was just a random letter. I was mostly testing whether `;` specifically threw the exception, or if that was a red herring.

**Comment by srjfoo** [comment]
> To be clear, I wasn't proposing Q. It was just a random letter. I was mostly testing whether `;` specifically threw the exception, or if that was a red herring.

That's fair, and I thought maybe that was the case, but `Q` was definitely a trigger 🤣 

Have you tried other non-alpha characters? Or combinations, such as `Cmd+Option`/`Ctrl+Alt` with `;`?

**Comment by windymilla** [comment]
Quite probably my fault - I expect I can use `Cmd/Ctrl+semicolon` instead of `Cmd/Ctrl+;` which will probably be fine. I'll look into it.
