### ISSUE TITLE
Linux traceback when menu bar is clicked

### ISSUE THREAD

**Issue by windymilla** [DistributedProofreaders/guiguts-py#470]
Traceback:

> 22:33:25: ERROR - Tkinter Exception
Traceback (most recent call last):
  File "/usr/lib/python3.11/tkinter/__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "/mnt/c/dp/guiguts-py/src/guiguts/maintext.py", line 476, in break_func
    func_ret = func(event)
               ^^^^^^^^^^^
  File "/mnt/c/dp/guiguts-py/src/guiguts/maintext.py", line 333, in text_peer_focus_track
    widget = parent.focus_get()
             ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/tkinter/__init__.py", line 805, in focus_get
    return self._nametowidget(name)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/tkinter/__init__.py", line 1563, in nametowidget
    w = w.children[n]
        ~~~~~~~~~~^^^
KeyError: '#!menu'

**Comment by windymilla** [comment]
Fixed by #471
